[tool.poetry]
name = "database-interface"
version = "0.1.0"
description = ""
authors = ["cbarne02 <Christopher.Barnett@tufts.edu>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.1"
PyMySQL = "^1.0.2"
SQLAlchemy = "^1.4.32"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
