[project]
name = "database-interface"
version = "0.1.6"
description = "code to abstract working with rt-analytics database"
authors = ["cbarne02 <Christopher.Barnett@tufts.edu>"]

[build-system]
requires = [
    "setuptools",
    "some-build-toolkit",
]
build-backend = "setuptools.build_meta"
